<?php

namespace Database\Seeders;

use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a test user
        $user = User::firstOrCreate(
            ['email' => 'test@hovertask.com'],
            [
                'fname' => 'Test',
                'lname' => 'User',
                'phone' => '08123456789',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
            ]
        );

        // Create sample Social/Engagement Tasks
        $engagementTasks = [
            [
                'title' => 'Like and Follow Our Instagram Post',
                'description' => 'Help us increase our social media presence by liking and following our latest Instagram post. Easy task that takes less than 2 minutes!',
                'platforms' => 'instagram',
                'task_amount' => 5000,
                'task_type' => 1,
                'task_count_total' => 100,
                'task_count_remaining' => 85,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 50,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Share WhatsApp Status',
                'description' => 'Share our promotional message to your WhatsApp status to help us reach more customers.',
                'platforms' => 'whatsapp',
                'task_amount' => 3000,
                'task_type' => 1,
                'task_count_total' => 50,
                'task_count_remaining' => 45,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 60,
                'start_date' => now(),
                'due_date' => now()->addDays(5),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Retweet and Like Our X Post',
                'description' => 'Help us trend on X/Twitter by retweeting and liking our promotional post.',
                'platforms' => 'x',
                'task_amount' => 4000,
                'task_type' => 1,
                'task_count_total' => 80,
                'task_count_remaining' => 72,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 50,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Comment on Facebook Post',
                'description' => 'Leave a positive comment on our Facebook promotional post to boost engagement.',
                'platforms' => 'facebook',
                'task_amount' => 2500,
                'task_type' => 1,
                'task_count_total' => 50,
                'task_count_remaining' => 42,
                'status' => 'active',
                'priority' => 'low',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 50,
                'start_date' => now(),
                'due_date' => now()->addDays(10),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Create TikTok Video Review',
                'description' => 'Create a short video reviewing our product and post it on TikTok.',
                'platforms' => 'tiktok',
                'task_amount' => 15000,
                'task_type' => 1,
                'task_count_total' => 20,
                'task_count_remaining' => 18,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 750,
                'start_date' => now(),
                'due_date' => now()->addDays(14),
                'task_category' => 'engagement',
            ],
            // Additional social tasks for Earn page
            [
                'title' => 'Watch YouTube Video & Like',
                'description' => 'Watch our promotional YouTube video and like it to help boost our video ranking.',
                'platforms' => 'youtube',
                'task_amount' => 2000,
                'task_type' => 1,
                'task_count_total' => 200,
                'task_count_remaining' => 180,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'video',
                'location' => 'Nigeria',
                'payment_per_task' => 10,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Join Telegram Channel',
                'description' => 'Join our Telegram channel and stay updated with our latest offers and news.',
                'platforms' => 'telegram',
                'task_amount' => 1500,
                'task_type' => 1,
                'task_count_total' => 100,
                'task_count_remaining' => 95,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 15,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Subscribe to YouTube Channel',
                'description' => 'Subscribe to our YouTube channel and enable notifications.',
                'platforms' => 'youtube',
                'task_amount' => 1000,
                'task_type' => 1,
                'task_count_total' => 150,
                'task_count_remaining' => 140,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'video',
                'location' => 'Nigeria',
                'payment_per_task' => 10,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Follow Us on Instagram',
                'description' => 'Follow our Instagram account @hovertask to never miss our updates.',
                'platforms' => 'instagram',
                'task_amount' => 2000,
                'task_type' => 1,
                'task_count_total' => 200,
                'task_count_remaining' => 190,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 10,
                'start_date' => now(),
                'due_date' => now()->addDays(14),
                'task_category' => 'engagement',
            ],
            [
                'title' => 'Share Post to Facebook Group',
                'description' => 'Share our promotional post to at least 3 Facebook groups you are a member of.',
                'platforms' => 'facebook',
                'task_amount' => 5000,
                'task_type' => 1,
                'task_count_total' => 50,
                'task_count_remaining' => 45,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'social_media',
                'location' => 'Nigeria',
                'payment_per_task' => 100,
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'engagement',
            ],
        ];

        foreach ($engagementTasks as $task) {
            Task::firstOrCreate(
                ['title' => $task['title'], 'user_id' => $user->id],
                array_merge($task, ['user_id' => $user->id])
            );
        }

        // Create sample Freelance Tasks
        $freelanceTasks = [
            [
                'title' => 'Logo Design for New Brand',
                'description' => 'We need a professional logo designed for our new tech startup. The brand is called "TechFlow" and focuses on fintech solutions. We need a modern, minimalist design that works well on both light and dark backgrounds.',
                'platforms' => 'design',
                'task_amount' => 50000,
                'task_type' => 2,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'design',
                'location' => 'Remote',
                'payment_per_task' => 50000,
                'fixed_price' => 50000,
                'pricing_type' => 'fixed',
                'experience_level' => 'intermediate',
                'project_duration' => '1_3_months',
                'skills_required' => 'Logo Design, Adobe Illustrator, Photoshop, Brand Identity',
                'start_date' => now(),
                'due_date' => now()->addDays(30),
                'task_category' => 'freelance',
            ],
            [
                'title' => 'WordPress Website Development',
                'description' => 'Looking for a WordPress developer to create a 5-page business website for our consulting firm. Must include contact form, blog section, and responsive design.',
                'platforms' => 'development',
                'task_amount' => 80000,
                'task_type' => 2,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'development',
                'location' => 'Remote',
                'payment_per_task' => 80000,
                'fixed_price' => 80000,
                'pricing_type' => 'fixed',
                'experience_level' => 'expert',
                'project_duration' => 'less_than_1_month',
                'skills_required' => 'WordPress, PHP, HTML, CSS, JavaScript',
                'start_date' => now(),
                'due_date' => now()->addDays(21),
                'task_category' => 'freelance',
            ],
            [
                'title' => 'Content Writing for Blog',
                'description' => 'We need 10 SEO-optimized blog posts about digital marketing topics. Each post should be 1500-2000 words.',
                'platforms' => 'writing',
                'task_amount' => 30000,
                'task_type' => 2,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'writing',
                'location' => 'Remote',
                'payment_per_task' => 30000,
                'fixed_price' => 30000,
                'pricing_type' => 'fixed',
                'experience_level' => 'intermediate',
                'project_duration' => '1_3_months',
                'skills_required' => 'Content Writing, SEO, Digital Marketing',
                'start_date' => now(),
                'due_date' => now()->addDays(45),
                'task_category' => 'freelance',
            ],
            [
                'title' => 'Social Media Manager Needed',
                'description' => 'Looking for a social media manager to handle our Instagram and Facebook accounts for 3 months. Must create content, schedule posts, and engage with followers.',
                'platforms' => 'marketing',
                'task_amount' => 120000,
                'task_type' => 2,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'marketing',
                'location' => 'Remote',
                'payment_per_task' => 40000,
                'hourly_rate' => 5000,
                'pricing_type' => 'hourly',
                'experience_level' => 'intermediate',
                'project_duration' => '3_6_months',
                'skills_required' => 'Social Media Management, Content Creation, Facebook, Instagram',
                'start_date' => now(),
                'due_date' => now()->addDays(90),
                'task_category' => 'freelance',
            ],
        ];

        foreach ($freelanceTasks as $task) {
            Task::firstOrCreate(
                ['title' => $task['title'], 'user_id' => $user->id],
                array_merge($task, ['user_id' => $user->id])
            );
        }

        // Create sample Jobs
        $jobs = [
            [
                'title' => 'Senior Software Engineer',
                'description' => 'We are looking for a Senior Software Engineer to join our growing tech team. You will be responsible for designing, developing, and maintaining our web applications. Must have experience with Laravel, React, and cloud services.',
                'platforms' => 'technology',
                'task_amount' => 300000,
                'task_type' => 3,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'technology',
                'job_location' => 'Lagos, Nigeria',
                'salary_range_min' => 200000,
                'salary_range_max' => 350000,
                'job_type' => 'full-time',
                'company_name' => 'TechInnovate Ltd',
                'qualifications_required' => "• 5+ years of software development experience\n• Proficiency in Laravel and React\n• Bachelor's degree in Computer Science or related field\n• Experience with AWS or Azure\n• Strong problem-solving skills",
                'job_benefits' => "• Health Insurance\n• Remote Work Options\n• Annual Leave\n• Training & Development\n• Performance Bonus",
                'application_deadline' => now()->addDays(30),
                'start_date' => now(),
                'due_date' => now()->addDays(30),
                'task_category' => 'job',
            ],
            [
                'title' => 'Digital Marketing Manager',
                'description' => 'Join our marketing team as a Digital Marketing Manager. You will be responsible for planning, implementing, and managing our overall digital marketing strategy.',
                'platforms' => 'marketing',
                'task_amount' => 180000,
                'task_type' => 3,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'high',
                'category' => 'marketing',
                'job_location' => 'Abuja, Nigeria',
                'salary_range_min' => 150000,
                'salary_range_max' => 200000,
                'job_type' => 'full-time',
                'company_name' => 'GrowthMarketing Inc',
                'qualifications_required' => "• 3+ years in digital marketing\n• Experience with SEO, PPC, and social media marketing\n• Google Analytics certification\n• Bachelor's in Marketing or related field\n• Excellent communication skills",
                'job_benefits' => "• Health Insurance\n• 13th Month Bonus\n• Professional Development\n• Flexible Hours",
                'application_deadline' => now()->addDays(21),
                'start_date' => now(),
                'due_date' => now()->addDays(21),
                'task_category' => 'job',
            ],
            [
                'title' => 'Graphic Designer (Part-time)',
                'description' => 'We are looking for a talented Graphic Designer to create visual concepts for our brand. This is a part-time position with flexible hours.',
                'platforms' => 'design',
                'task_amount' => 60000,
                'task_type' => 3,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'design',
                'job_location' => 'Remote',
                'salary_range_min' => 50000,
                'salary_range_max' => 80000,
                'job_type' => 'part-time',
                'company_name' => 'CreativeStudio',
                'qualifications_required' => "• Portfolio showcasing design work\n• Proficiency in Adobe Creative Suite\n• Understanding of design principles\n• Ability to meet deadlines\n• Good communication skills",
                'job_benefits' => "• Flexible Schedule\n• Remote Work\n• Creative Freedom",
                'application_deadline' => now()->addDays(14),
                'start_date' => now(),
                'due_date' => now()->addDays(14),
                'task_category' => 'job',
            ],
            [
                'title' => 'Customer Support Representative',
                'description' => 'We need a friendly and professional Customer Support Representative to assist our customers via phone, email, and chat.',
                'platforms' => 'other',
                'task_amount' => 96000,
                'task_type' => 3,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'medium',
                'category' => 'other',
                'job_location' => 'Lagos, Nigeria',
                'salary_range_min' => 80000,
                'salary_range_max' => 120000,
                'job_type' => 'full-time',
                'company_name' => 'CustomerFirst Ltd',
                'qualifications_required' => "• Minimum of OND/HND\n• Excellent communication skills\n• Problem-solving abilities\n• Customer service experience\n• Basic computer skills",
                'job_benefits' => "• Health Insurance\n• Paid Training\n• Career Growth\n• Shift Allowance",
                'application_deadline' => now()->addDays(7),
                'start_date' => now(),
                'due_date' => now()->addDays(7),
                'task_category' => 'job',
            ],
            [
                'title' => 'UI/UX Designer Internship',
                'description' => 'We are offering an internship opportunity for aspiring UI/UX designers. This is a great chance to learn from experienced professionals and build your portfolio.',
                'platforms' => 'design',
                'task_amount' => 30000,
                'task_type' => 3,
                'task_count_total' => 1,
                'task_count_remaining' => 1,
                'status' => 'active',
                'priority' => 'low',
                'category' => 'design',
                'job_location' => 'Lagos, Nigeria',
                'salary_range_min' => 25000,
                'salary_range_max' => 30000,
                'job_type' => 'internship',
                'company_name' => 'DesignHub Africa',
                'qualifications_required' => "• Currently studying or recently graduated in Design-related field\n• Basic knowledge of Figma or Adobe XD\n• Eagerness to learn\n• Portfolio (if any)\n• Good teamwork skills",
                'job_benefits' => "• Mentorship\n• Portfolio Building\n• Certificate of Completion\n• Potential for full-time employment",
                'application_deadline' => now()->addDays(14),
                'start_date' => now(),
                'due_date' => now()->addDays(14),
                'task_category' => 'job',
            ],
        ];

        foreach ($jobs as $task) {
            Task::firstOrCreate(
                ['title' => $task['title'], 'user_id' => $user->id],
                array_merge($task, ['user_id' => $user->id])
            );
        }

        echo "✅ Sample tasks seeded:\n";
        echo "   - 10 Social/Engagement Tasks\n";
        echo "   - 4 Freelance Tasks\n";
        echo "   - 5 Job Opportunities\n";
    }
}
